### PR TITLE
Rubocop setup

### PR DESCRIPTION
**Pull request by bhavanisarma**
I have installed rubocop. But suggest you guys to install rubocop pluginn in sublime.

### CODE REVIEW

**Comment by dbielza** [comment]
I think the code looks good. It says there are conflicts, which I am not sure what that means.

**Comment by spp1991** [comment]
> I think the code looks good. It says there are conflicts, which I am not sure what that means. Does it mean we just have to install Rubocop to our sublime text?

Conflict means , some changes  made in this pull request conflicts with code of listed files in master branch. I believe , new push of code by @bhavanisarma  after she performs rebasing the code of her local project code repository for this branch with master branch of Github,  will remove the conflict.

**Comment by spp1991** [comment]
> I have installed rubocop. But suggest you guys to install rubocop pluginn in sublime.

Hi @bhavanisarma , can you resolve the conflict for this brnach? I can do that but I believe you will be better person to resolve it as you implemented the rubocop

**Comment by bhavanisarma** [comment]
> > I have installed rubocop. But suggest you guys to install rubocop pluginn in sublime.
> 
> Hi @bhavanisarma , can you resolve the conflict for this brnach? I can do that but I believe you will be better person to resolve it as you implemented the rubocop

Hi Sunny and Daniel
I went through these conflicts and wonder what to keep and what to delete. After I ran "rubocop autocorrect" command, syntax in lots of files has changed in accordance  with the ruby style guide. Sunday I will discuss with my mentor and resolve conflicts.  I think if you guys install rubocop plugin, these changes may not be necessary.

**Pull request merged**
